class:
  wdbasic: Ext_TC_Marketing_Feedback_Questionary
  data: Ext_TC_Marketing_Feedback_Questionary_Gui2_Data
id:
  column: id
  alias: tc_fqn
access: 
  - core_marketing_questionnaires
  - ""
bars:
  - 
    position: top
    type: ""
    elements:
     -
        element: inputfilter
        label: Suche
        searchtype: LIKE
        column:
          - name
        alias:
          - tc_fqn

  -
    position: top
    type: ""
    elements:
      -
        element: icon_new
        dialog:
          - Ext_TC_Marketing_Feedback_Questionary_Gui2_Data
          - getDialog
      -
        element: icon_edit
        dialog:
          - Ext_TC_Marketing_Feedback_Questionary_Gui2_Data
          - getDialog
      -
        element: icon_delete
      - 
        element: icon_duplicate
        access:
          - core_marketing_questionnaires
          - duplicate
columns:
  -
    visible: true
    title: Name
    column: name
    alias: tc_fqn
    width: name
    resize: true
      
default_columns:
   -
     title: Ersteller
     column: creator_id
     width: user_name
     resize: false
     format: Ext_Gui2_View_Format_UserName
     sortable: true
   -
     title: Erstellt
     column: created
     width: date
     resize: false
     format: Ext_TC_Gui2_Format_Date
     sortable: true
   -
     title: Bearbeiter
     column: editor_id
     width: editor_id
     resize: false
     format: Ext_Gui2_View_Format_UserName
     sortable: true
   -
     title: Ver√§ndert
     column: changed
     width: date
     resize: false
     format: Ext_TC_Gui2_Format_Date
     sortable: true
    

  
