class:
  wdbasic: Multi\Entity\Category
orderby : 
  - Multi\Gui2\Data\Categories
  - getOrderBy
id:
  column: id
  alias: opa
title: "Kategorien"
description: "Multidata"
access: "office_config"
bars:
    - 
      position: top
      set: []
      type: ""
      elements:
        -
          element: inputfilter
          label: Suche
          searchtype: LIKE
          column: 
            - name
          alias: 
            -
          access:
    - 
      position: top
      set: []
      type: ""
      access: []
      elements: 
        -
          element: icon_new
          dialog:
            - Multi\Gui2\Data\Categories
            - getDialog
        - 
          element: icon_edit
          dialog:
            - Multi\Gui2\Data\Categories
            - getDialog
        - 
          element: icon_delete
columns:
  -
    title: Name
    column: name
    description: ""
    resize: true
    width: name
default_columns:
  -
    visible: true
    title: Ersteller
    format: Ext_Gui2_View_Format_UserName
    format_params: true
    column: creator_id
    alias: ""
    width: user_name
    resize: false
    sortable: true
  -
    visible: true
    title: Erstellt
    format: Ext_Gui2_View_Format_Date
    column: created
    width: date
    resize: false
    sortable: true
  -
    visible: true
    title: Bearbeiter
    format: Ext_Gui2_View_Format_UserName
    format_params: true
    column: editor_id
    width: user_name
    resize: false
    sortable: true
  -
    visible: true
    title: Bearbeitet
    format: Ext_Gui2_View_Format_Date
    column: changed
    width: date
    resize: false
    sortable: true