hash: 1fbc5b752b512c630db3036884619423
class:
  wdbasic: Ext_Thebing_Accommodation_Meal
  data: Ext_Thebing_Accommodation_Meal_Gui2
access: thebing_accommodation_meals
id:
  column: id
  alias: kam
sortable: true
only_pagecount: true
designer: 
  flex: meals
orderby:
  - Ext_Thebing_Accommodation_Meal_Gui2
  - getOrderby
bars:
  -
    position: top
    elements:
     -
        element: inputfilter
        label: Suche
        alias: kam
        searchtype: LIKE
        call:
          - Ext_Thebing_Accommodation_Meal_Gui2
          - manipulateSearchFilter
     -
        element: validfilter
        label: Gültigkeit
  -
    position: top
    elements:
     -
        element: icon_new
        dialog:
          - Ext_Thebing_Accommodation_Meal_Gui2
          - getDialog
     -
        element: icon_edit
        dialog:
          - Ext_Thebing_Accommodation_Meal_Gui2
          - getDialog
     -
        element: icon_delete
     -
        element: icon_deactivate
        access: thebing_accommodation_meals_deactivate
        
columns:
  - 
    title: Bezeichnung
    column: name
    width: name
    resize: true
    i18n: 
      pass_language: true
      interface: frontend      
  - 
    title: Kürzel	
    column: short
    width: short_name  
    i18n: 
      pass_language: true
      interface: frontend    
  - 
    title: Schulen	
    column: schools
    width: name
    access: thebing_accommodation_mealplan
    format: Ext_Thebing_Gui2_Format_Multiselect
    format_params: 
      - [Ext_Thebing_Client, getSchoolList, true]
  - 
    title: Gültig bis	
    column: valid_until
    width: date
    format: Ext_Thebing_Gui2_Format_Date