hash: 6555764496990bb56bd0e1ec4c8b109b
class:
  wdbasic: Ext_Thebing_Tuition_Classroom
  data: Ext_Thebing_Tuition_Gui2_Classrooms_Gui2
access: 
  - thebing_tuition_resource_classrooms
  - ""
sortable: true
only_pagecount: true
designer: 
  flex: tuition_course_classrooms
multiple_selection: false
id:
  column: id
  alias: kc
orderby:
  - Ext_Thebing_Tuition_Gui2_Classrooms_Gui2
  - getOrderby
where:
  - Ext_Thebing_Tuition_Gui2_Classrooms_Gui2
  - getWhere
limit: 10000
bars:
  -
    position: top
    elements:
     -
        element: inputfilter
        label: Suche
        alias: 
          - kc
          - kc
          - ksb
          - ksf
        column:
          - id
          - name
          - title
          - title  
        searchtype: LIKE
     -
        element: seperator
     -
        element: selectfilter
        label: Online
        label_as_item: true
        id: online_filter
        entries:
          - Ext_Thebing_Util
          - getYesNoArray
          - false
        filter_query:
          yes: ' `kc`.`online` = 1 '
          no: ' `kc`.`online` = 0 '
     -
       element: selectfilter
       label: Lehrerportal
       label_as_item: true
       id: teacher_portal_filter
       entries:
         - Ext_Thebing_Util
         - getYesNoArray
         - false
       filter_query:
         yes: ' `kc`.`teacher_portal` = 1 '
         no: ' `kc`.`teacher_portal` = 0 '
     -
        element: seperator
     -
        element: validfilter
        label: G체ltigkeit          
  -
    position: top
    elements:
     -
        element: icon_new
        dialog:
          - Ext_Thebing_Tuition_Gui2_Classrooms_Gui2
          - getDialog
     -
        element: icon_edit
        dialog:
          - Ext_Thebing_Tuition_Gui2_Classrooms_Gui2
          - getDialog
     -
        element: icon_delete
     - 
        element: icon_deactivate
        access: thebing_tuition_resource_classrooms_deactivate
columns:
  -
    title: Klassenzimmer
    column: name
    width: name
    alias: kc
    resize: true
    inplace_editor: 0
  - 
    title: Etage
    column: floor
    width: name
    resize: false
    inplace_editor: 0
  - 
    title: Geb채ude	
    column: building
    width: name
    resize: false
    inplace_editor: 0
  - 
    title: Online
    column: online
    width: yes_no
    alias: kc
    format: Ext_Gui2_View_Format_YesNo
    resize: false
    inplace_editor: 0
  -
    title: Lehrerportal
    column: teacher_portal
    width: yes_no
    alias: kc
    format: Ext_Gui2_View_Format_YesNo
    resize: false
    inplace_editor: 0
  - 
    title: Max. Anzahl Sch체ler	
    column: max_students
    width: number
    resize: false
    small: true
    alias: kc
    format: Ext_Thebing_Gui2_Format_Int
    inplace_editor: 0
  - 
    title: Kommentar	
    column: comment
    width: long_description
    resize: false
    inplace_editor: 0
    default: false
    alias: kc
  - 
    title: Eigenschaften	
    column: tags 
    width: long_description
    format: \TsTuition\Gui2\Format\Classroom\Tags
    default: false
    resize: false
    alias: kc
  -
    title: G체ltig bis	
    column: valid_until  
    width: date
    default: false
    format: Ext_TC_Gui2_Format_Date