hash: 29ec98e98434ac1526f90baabb578d19
class:
  wdbasic: Ext_Thebing_Management_Page
  data: Ext_Thebing_Management_Page_Gui2
  js: AccessMatrixGui
js:
  - [gui2/gui2.js, tc]
  - [js/access_matrix.js, tc]
access: thebing_management_pages
id:
  column: id
  alias: kmp
limit: 30
limit_selection: false
multiple_selection: false
bars:
  -
    position: top
    elements:
     -
        element: inputfilter
        label: Suche
        column: 
          - title
        alias: kmp
        id: search
        searchtype: LIKE
  -  
    position: top
    elements:
     -
        element: icon_new
        dialog:
          - Ext_Thebing_Management_Page_Gui2
          - getDialog
     -
        element: icon_edit
        dialog:
          - Ext_Thebing_Management_Page_Gui2
          - getDialog
     -
        element: icon_delete
     -
        element: labelgroup
        label: Zugriff   
     - 
        element: icon
        access:
          - core_admin_exchangerate
          - exchangerate_view
        task: openDialog
        action: openAccessDialog
        dialog:
          - Ext_Thebing_Management_Page_Gui2
          - getDialog
        img: 
          - Ext_Thebing_Util
          - getIcon
          - access   
columns:
  - 
    title: Titel
    column: title
    width: name
  - 
    title: Statistiken
    column: statistics
    width: name
    resize: true