hash: 909dc5c3a7fd704afcafb6379b4aa879
class:
  wdbasic: Ext_Thebing_Admin_Reason
  data: Ext_Thebing_Admin_Reason_Gui2
access: thebing_admin_reasons
id:
  column: id
  alias: ''
where:
  - Ext_Thebing_Admin_Reason_Gui2
  - getWhere
limit_selection: false
multiple_selection: false
bars:
  -
    position: top
    elements:
     -
        element: inputfilter
        label: Suche
        column: 
          - name
        id: search
        searchtype: LIKE
  -  
    position: top
    elements:
     -
        element: icon_new
        dialog:
          - Ext_Thebing_Admin_Reason_Gui2
          - getDialog
     -
        element: icon_edit
        dialog:
          - Ext_Thebing_Admin_Reason_Gui2
          - getDialog
     -
        element: icon_delete
columns:
  - 
    title: Grund
    column: name
    width: name
    alias: ''
    resize: true
    data: name