hash: 1360e96ff4b207f8a97bba0458503029
class:
  wdbasic: Ext_Thebing_Marketing_TeacherCategories
  data: \Ts\Gui2\Data\TeacherCategories
access: thebing_marketing_teachercategories
id:
  alias: kckt
  column: id
only_pagecount: true
orderby:
  - \Ts\Gui2\Data\TeacherCategories
  - getOrderby
where:
  - \Ts\Gui2\Data\TeacherCategories
  - getWhere  
bars:
  -
    position: top
    elements:
     -
        element: inputfilter
        label: Suche
        column: name
        searchtype: LIKE
  -
    position: top
    elements:
     -
        element: icon_new
        dialog:
          - \Ts\Gui2\Data\TeacherCategories
          - getDialog
     -
        element: icon_edit
        dialog:
          - \Ts\Gui2\Data\TeacherCategories
          - getDialog
     -
        element: icon_delete
columns:
  - 
    title: Name
    column: name
    width: name
    resize: true  